[package]
name = "simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
# wgpu = "0.18"
winit = "0.30"
# env_logger = "0.10"
# pollster = "0.3"
# bytemuck = { version = "1.14", features = ["derive"] }
nalgebra-glm = "0.3"
